#
#
#
version: "3.9"

services:
  #
  # Cassandra Server
  #
  cassandra:
    image: cassandra:4.1
    hostname: cassandra
    container_name: cassandra
    restart: always
    ports:
      - "7000:7000"
      - "7001:7001"  #
      - "7199:7199"  # JMX
      - "9042:9042"  # Native Transport
      - "9160:9160"  # Thrift Clients
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_cassandra_data:/var/lib/cassandra
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_cassandra_data:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net