#
#
#
version: "3.9"

services:
  #
  # Zookeeper Server
  #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    healthcheck:
      test: curl -f http://zookeeper.sandbox.net:8080/commands || exit 1
      retries: 20
      interval: 10s
    ports:
      - "2181:2181"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/zookeeper/secrets
      - /apps/sandbox/zookeeper/hadoop311/data:/var/lib/zookeeper/data
      - /apps/sandbox/zookeeper/hadoop311/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_UNSIGNED: "true"

  #
  # Hbase Cluster
  #
  hmaster:
    image: brijeshdhaker/hbase-master:2.4.6
    hostname: hmaster.sandbox.net
    container_name: hmaster
    healthcheck:
      test: curl -f http://hmaster.sandbox.net:16010 || exit 1
      retries: 20
      interval: 10s
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181"
    env_file:
      - envs/docker_hbase.env
    ports:
      - "16000:16000"
      - "16010:16010"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_311:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop

  #
  hregion:
    image: brijeshdhaker/hbase-regionserver:2.4.6
    hostname: hregion.sandbox.net
    container_name: hregion
    healthcheck:
      test: curl -f http://hregion.sandbox.net:16030 || exit 1
      retries: 20
      interval: 10s
    env_file:
      - envs/docker_hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode.sandbox.net:9870 zookeeper.sandbox.net:2181 hmaster.sandbox.net:16010"
    ports:
      - "16020:16020"
      - "16030:16030"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_hadoop_311:/opt/hadoop
      - ./conf/hadoop/client:/opt/hadoop/etc/hadoop

#
volumes:
  #
  sandbox_apps_path:
    external: true
  sandbox_security_secrets:
    external: true
  #
  sandbox_zookeeper_data:
    external: true
  sandbox_zookeeper_log:
    external: true
  sandbox_hadoop_311:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
