#
#
#
version: "3.9"

services:
  #
  # Zookeeper Server
  #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - sandbox3_apps_hostpath:/apps/hostpath
      - sandbox3_zookeeper_secrets:/etc/zookeeper/secrets
      - sandbox3_zookeeper_data:/var/lib/zookeeper/data
      - sandbox3_zookeeper_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_UNSIGNED: "true"

  #
  # Hbase Server
  #
  hbase-master:
    image: brijeshdhaker/hbase-master:2.4.9
    hostname: hbase-master
    container_name: hbase-master
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 zookeeper:2181"
    env_file:
      - sandbox3.env
    ports:
      - "16000:16000"
      - "16010:16010"
    volumes:
      - sandbox3_apps_hostpath:/apps/hostpath

  #
  hbase-region:
    image: brijeshdhaker/hbase-regionserver:2.4.9
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - sandbox3.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 zookeeper:2181 hbase-master:16010"
    ports:
      - "16020:16020"
      - "16030:16030"
    volumes:
      - sandbox3_apps_hostpath:/apps/hostpath

#
volumes:
  sandbox3_apps_hostpath:
    external: true
  sandbox3_zookeeper_secrets:
    external: true
  sandbox3_zookeeper_data:
    external: true
  sandbox3_zookeeper_log:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net
