#
# docker volume create --name sandbox_host_path --opt type=none --opt device=/apps/hostpath --opt o=bind
# docker volume create --name sandbox_base_path --opt type=none --opt device=/apps/sandbox --opt o=bind
# docker volume create --name sandbox_hadoop_334 --opt type=none --opt device=/opt/hadoop-3.3.4 --opt o=bind
#
# docker volume create --name sandbox_hadoop_334_dfs --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/dfs --opt o=bind
# docker volume create --name sandbox_hadoop_334_yarn --opt type=none --opt device=/apps/sandbox/hadoop-3.3.4/yarn --opt o=bind
#

version: "3.9"

services:
  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.3.4
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
    environment:
      - CLUSTER_NAME=docker-sandbox
    env_file:
      - envs/docker_hadoop334.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.3.4
    container_name: datanode
    hostname: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_dfs:/hadoop/dfs
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - envs/docker_hadoop334.env

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.3.4
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
      - "8032:8032"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - envs/docker_hadoop334.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.3.4
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - envs/docker_hadoop334.env


  #
  # YARN History Server
  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.3.4
    container_name: historyserver
    hostname: historyserver
    restart: always
    ports:
      - "19888:19888"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop_334_yarn:/yarn
    env_file:
      - envs/docker_hadoop334.env

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_hadoop_334:
    external: true
  sandbox_hadoop_334_dfs:
    external: true
  sandbox_hadoop_334_yarn:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net