#
#
#
version: "3.9"

services:
  #
  # HDFS Sandbox
  #

  #
  namenode:
    image: brijeshdhaker/hadoop-namenode:3.3.4
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - sandbox_hadoop_dfs_name:/hadoop/dfs/name
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      - CLUSTER_NAME=docker-sandbox
    env_file:
      - sandbox_3_3_4.env

  #
  datanode:
    image: brijeshdhaker/hadoop-datanode:3.3.4
    container_name: datanode
    hostname: datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    restart: always
    volumes:
      - sandbox_hadoop_dfs_data:/hadoop/dfs/data
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - sandbox_3_3_4.env

  #
  # YARN Sandbox
  #

  #
  resourcemanager:
    image: brijeshdhaker/hadoop-resourcemanager:3.3.4
    container_name: resourcemanager
    hostname: resourcemanager
    restart: always
    ports:
      - "8088:8088"
      - "8032:8032"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - sandbox_3_3_4.env

  #
  nodemanager:
    image: brijeshdhaker/hadoop-nodemanager:3.3.4
    container_name: nodemanager
    hostname: nodemanager
    restart: always
    ports:
      - "8042:8042"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - sandbox_3_3_4.env

  #
  historyserver:
    image: brijeshdhaker/hadoop-historyserver:3.3.4
    container_name: historyserver
    hostname: historyserver
    restart: always
    ports:
      - "19888:19888"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    volumes:
      - sandbox_yarn_history:/tmp/yarn/history
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
    env_file:
      - sandbox_3_3_4.env

  #
  # Mysql Database Server
  #

  #
  mysqlserver:
    image: mysql/mysql-server:8.0.28
    container_name: mysqlserver
    hostname: mysqlserver
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_mysql_conf:/etc/mysql/conf.d
      - sandbox_mysql_data:/var/lib/mysql
    env_file:
      - sandbox_3_3_4.env

  #
  # Hive Server
  #

  #
  hive-metastore:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-metastore
    container_name: hive-metastore
    env_file:
      - sandbox_3_3_4.env
    command: /opt/hive-3.1.2/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "mysqlserver:3306"
    links:
      - mysqlserver
    ports:
      - "9083:9083"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox

  #
  hive-server:
    image: brijeshdhaker/hive:3.1.2
    hostname: hive-server
    container_name: hive-server
    env_file:
      - sandbox_3_3_4.env
    links:
      - hive-metastore
      - namenode
      - datanode
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://mysqlserver/metastore?createDatabaseIfNotExist=true;autoReconnect=true;useSSL=false"
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox

  #
  # Spark History Server
  #

  #
  spark-historyserver:
    image: brijeshdhaker/spark-historyserver:3.3.1
    container_name: spark-historyserver
    hostname: spark-historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    depends_on:
      - namenode
      - datanode
    ports:
      - "18080:18080"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop:/opt/hadoop-3.3.4

  #
  # Zeppelin Notebook
  #

  #
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    hostname: zeppelin
    env_file:
      - sandbox_3_3_4.env
    ports:
      - "9080:8080"
      - "4040:4040"
    volumes:
      - sandbox_host_path:/apps/hostpath
      - sandbox_base_path:/apps/sandbox
      - sandbox_hadoop:/opt/hadoop-3.3.4
      - sandbox_hbase:/opt/hbase-2.4.9
      - sandbox_hbase_client:/opt/hbase-client
      - sandbox_hive:/opt/hive-3.1.2
      - sandbox_spark:/opt/spark-3.3.1
      - sandbox_zeppelin:/opt/zeppelin
      - sandbox_zeppelin_notebook:/opt/notebook
#      - sandbox_zeppelin_conf:/opt/zeppelin/conf
#      - sandbox_m2:/opt/zeppelin/.m2
#      - sandbox_ivy2:/opt/zeppelin/.ivy2

#
volumes:
  sandbox_host_path:
    external: true
  sandbox_base_path:
    external: true
  sandbox_m2:
    external: true
  sandbox_ivy2:
    external: true
  sandbox_hadoop_data:
    external: true
  sandbox_hadoop_dfs_name:
    external: true
  sandbox_hadoop_dfs_data:
    external: true
  sandbox_yarn_history:
    external: true
  sandbox_mysql_data:
    external: true
  sandbox_mysql_conf:
    external: true
  sandbox_postgres_data:
    external: true
  sandbox_postgres_conf:
    external: true
  sandbox_postgres_init:
    external: true
  sandbox_zeppelin:
    external: true
  sandbox_zeppelin_conf:
    external: true
  sandbox_zeppelin_notebook:
    external: true
  sandbox_hadoop:
    external: true
  sandbox_hbase:
    external: true
  sandbox_hbase_client:
    external: true
  sandbox_hive:
    external: true
  sandbox_spark:
    external: true

#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox-bigdata.net
