#
# mkdir -p /apps/sandbox/influxdb/data
# sudo chmod -Rf 777 /apps/sandbox/influxdb
#

#
# docker volume create --name sandbox_influxdb_config --opt type=none --opt device=/apps/sandbox/influxdb --opt o=bind
# docker volume create --name sandbox_influxdb_data --opt type=none --opt device=/apps/sandbox/influxdb/data --opt o=bind
#
# docker volume create --name sandbox_influxdb_config --opt type=none --opt device=/apps/sandbox/influxdb --opt o=bind
# docker volume create --name sandbox_influxdb_data --opt type=none --opt device=/apps/sandbox/influxdb/data --opt o=bind
#

#
# docker exec -it influxdb /usr/bin/influx
#

#
#
#
---

version: "3.9"

services:
  #
  # influxdb Server
  #
#  influxdb:
#    image: docker.io/influxdb:1.8.10-alpine
#    hostname: influxdb
#    container_name: influxdb
#    restart: always
#    ports:
#      - "8086:8086"  # api
#      - "2003:2003"  # graphite
##      - "8088:8088"  # rpc
#    volumes:
#      - sandbox_host_path:/apps/hostpath
#      - sandbox_base_path:/apps/sandbox
#      - sandbox_influxdb_config:/etc/influxdb
#      - sandbox_influxdb_data:/var/lib/influxdb
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes

  influxdb:
    image: docker.io/influxdb:latest
    hostname: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"  # api
      - "2003:2003"  # graphite
#      - "8088:8088"  # rpc
    volumes:
      - sandbox_apps_path:/apps
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


#
volumes:
  sandbox_apps_path:
    external: true
  sandbox_influxdb_config:
    external: true
  sandbox_influxdb_data:
    external: true
#
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net