---
#
version: '3.1'
#
services:
#
  mariadb:
    image: mariadb:10.3.27
    container_name: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - /apps/hostpath/mysql/conf:/etc/mysql/conf.d
      - /apps/hostpath/mysql/data:/var/lib/mysql
    environment:
      MYSQL_OPERATIONS_USER: operate
      MYSQL_OPERATIONS_PASSWORD: p@SSW0rd
      MYSQL_ROOT_PASSWORD: p@SSW0rd
      MYSQL_DATABASE: PUBLIC
      MYSQL_USER: developer
      MYSQL_PASSWORD: pDSSW0rd
    ports:
      - 3306:3306
#    networks:
#      - back-tier

#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 9090:8080
#    networks:
#      - back-tier
#

#
#networks:
#  default:
#    external:
#      name: bridge
#  backend:
#    driver: bridge
#