{
 "title": "Spark: Applications (JMX)",
 "description": "Spark Executors and Driver Level Metrics with filtering by service",
 "tags": [ "spark" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": "application_1675994320382_0001" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Drivers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"driver\",label_sparkoperator_k8s_io_app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "CPUs Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"resourcemanager\"}[1m])) by (id,name)",
     "legendFormat": "CPUs Used by Driver"
    },
    {
     "expr": "sum(container_resource_requests_cpu_cores{container=\"executor\", pod=~\"($app_name).*\"}) by (namespace)",
     "legendFormat": "CPUs Used by Executor"
    },
    {
     "expr": "sum(container_resource_requests_cpu_cores{pod=~\"($app_name).*\"}) by (namespace)",
     "legendFormat": "Total CPUs Used"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"nodemanager\"})",
     "legendFormat": "Mem Used by Driver"
    },
    {
     "expr": "spark_driver_jvm_heap_usage{app_id=\"$app_name\"}",
     "legendFormat": "Mem Used by Executors"
    },
    {
     "expr": "spark_executor_jvmheapmemory{app_id=\"$app_name\"}",
     "legendFormat": "Total Mem Used"
    }
   ]
  },
  {
   "title": "Executors Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"executor\",label_sparkoperator_k8s_io_app_name=~\"$app_name\"})"
    }
   ]
  },
  {
   "title": "Execution Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Driver Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_driver_jvm_total_max{app_id=~\"$app_name\"}",
     "legendFormat": "Heap max ({{app_id}})"
    },
    {
     "expr": "spark_driver_jvm_total_used{app_id=~\"$app_name\"}",
     "legendFormat": "Heap used ({{app_id}})"
    }
   ]
  },
  {
   "title": "Executor Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_jvmoffheapmemory{app_id=~\"$app_name\"}",
     "legendFormat": "Heap max ({{app_id}})"
    },
    {
     "expr": "spark_executor_jvmheapmemory{app_id=~\"$app_name\"}",
     "legendFormat": "Heap used ({{app_id}})"
    }
   ]
  },
  {
   "title": "BlockManager (on-heap memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_memory_maxonheapmem_mb{app_id=~\"$app_name\"}",
     "legendFormat": "Max On-Heap Memory  ({{app_id}})"
    },
    {
     "expr": "spark_driver_blockmanager_memory_onheapmemused_mb{app_id=~\"$app_name\"}",
     "legendFormat": "On-Heap Memory Used  ({{app_id}})"
    }
   ]
  },
  {
   "title": "BlockManager (off-heap memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_memory_maxoffheapmem_mb{app_id=~\"$app_name\"}",
     "legendFormat": "Max Off-Heap Memory ({{app_id}})"
    },
    {
     "expr": "spark_driver_blockmanager_memory_offheapmemused_mb{app_id=~\"$app_name\"}",
     "legendFormat": "Off-Heap Memory Used ({{app_id}})"
    }
   ]
  },
  {
   "title": "BlockManager (disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_blockmanager_disk_diskspaceused_mb{app_id=~\"$app_name\"}",
     "legendFormat": "Disk Space Used  ({{app_id}})"
    }
   ]
  },
  {
   "title": "DAG Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_job_alljobs{app_id=~\"$app_name\"}",
     "legendFormat": "All Jobs ({{app_id}})"
    },
    {
     "expr": "spark_driver_dagscheduler_job_activejobs{app_id=~\"$app_name\"}",
     "legendFormat": "Active Jobs ({{app_id}})"
    }
   ]
  },
  {
   "title": "Stages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_stage_runningstages{app_id=~\"$app_name\"}",
     "legendFormat": "Running Stages ({{app_id}})"
    },
    {
     "expr": "spark_driver_dagscheduler_stage_waitingstages{app_id=~\"$app_name\"}",
     "legendFormat": "Waiting Stages  ({{app_id}})"
    },
    {
     "expr": "spark_driver_dagscheduler_stage_failedstages{app_id=~\"$app_name\"}",
     "legendFormat": "Failed Stages ({{app_id}})"
    }
   ]
  }
 ]
}